[package]
name = "mklml_ffi"
version = "0.0.0"
edition = "2018"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[features]
default = ["mklml_intel"]
mklml_gnu = []
mklml_intel = []
fresh = ["bindgen"]

[build-dependencies]
bindgen = { version = "^0.46", optional = true }
